speaker_recognition_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("speaker_verification/", include("speaker_verification.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

speaker_verification/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter
from speaker_verification.api import UserModelViewSet, Predict
from . import views


router = DefaultRouter()
router.register(r'user', UserModelViewSet, basename='user-api')

urlpatterns = [
    path("", views.index, name="index"),
    path(r'api/v1/', include(router.urls)),
    path('speaker-verify', Predict.as_view())
    # path('register/', views.register, name='register'),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    
]

speaker_verification/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
	embedding = models.FileField(upload_to='embedding/', null=True)

speaker_verification/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['embedding']

speaker_verification/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import UserForm
import requests


# Create your views here.
def index(request):
    if request.method == 'POST':
        f = UserForm(request.POST, request.FILES)
        if f.is_valid():
            data = requests.post('http://127.0.0.1:8000/speaker_verification/speaker-verify', files=request.FILES)
            messages.success(request, f'{data}')
        else:
            messages.error(request, "Failed. Please check again the information")
            return render(request, "speaker_verification/index.html", {
        'form': f
    })

    return render(request, "speaker_verification/index.html", {
        'form': UserForm()
    })

speaker_verification/templates/speaker_verification/index.html
<html>
<body>

<h3>.wav File Upload</h3>
<form action="{% url 'index' %}" enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
</form>

<!-- <script>

    function verify(){
        fetch('http://127.0.0.1:8000/speaker_verification/speaker-verify/', {
        method: 'POST',
        body: formData
    })
    }



    const handleImageUpload = event => {
    const files = event.target.files
    const formData = new FormData()
    formData.append('myFile', files[0])

    fetch('http://127.0.0.1:8000/speaker_verification/speaker-verify/', {
        method: 'POST',
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        console.log(data)
    })
    .catch(error => {
        console.log(error)
    })
    }

    document.querySelector('#id_embedding').addEventListener('change', event => {
  handleImageUpload(event)})
</script> -->

</body>
</html>